### ISSUE TITLE
Documentation for nginx

### ISSUE THREAD

**Issue by denizdogan** [vint21h/django-xicon#3]
Would be nice if there was documentation on how to set this up with nginx so that the files are served as fast as possible without hitting WSGI.

**Comment by vint21h** [comment]
Hi,
I don't understand you, there are no files serving by Django, except of "manifest.json" and "browserconfig.xml" generating by Django views which are totally dynamical and must be rendered by on fly.

**Comment by denizdogan** [comment]
Alright, I must have misunderstood then, I thought that this was actually serving the favicons.
